authtoken: 1QqOxkpRRnI3Az72Pp0KdtDqeLw_5nZ8zn187XqPL6BjzYmT8
tunnels:
  httpbin:
    proto: http
    addr: 3636
    subdomain: alan-httpbin
  demo:
    proto: tcp
    addr: 5000
    hostname: demo.inconshreveable.com
    inspect: false